FROM ubuntu

MAINTAINER auguitar

RUN apt-get update && apt-get install -y emacs

CMD ["/usr/bin/emacs", "-f", "snake"]

#5x5
#blackbox
#solitaire
#adventure
#gomoku
#life
#snake
#tetris

#Commande build: docker build -t games .

#Commande build:  docker run --rm -ti games
