FROM python:3-alpine

MAINTAINER auguitar

RUN pip install speedtest-cli

ENTRYPOINT ["speedtest"]

#Commande build: docker build -t speed_test .

#Commande run: docker run --rm -ti speed_test 
