FROM ubuntu

MAINTAINER auguitar

RUN apt-get update && apt-get install -y telnet

ENTRYPOINT telnet towel.blinkenlights.nl

#Commande build: docker build -t star_wars .

#Commande run: docker run --rm -ri star_wars
